export const FETCH_PHOTO = "FETCH_PHOTO";
export const START_FETCH_PHOTO = "START_FETCH_PHOTO";
export const COMPLETE_FETCH_PHOTO = "COMPLETE_FETCH_PHOTO";
export const FAIL_FETCH_PHOTO = "FAIL_FETCH_PHOTO";
